[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "node dist/server.js"

[deploy.healthcheck]
path = "/v1/health"
interval = 30
timeout = 5
